services:
  - type: web
    name: plastik-ml-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && pip install gdown
    startCommand: python ml_api/ml_api.py
    envVars:
      - key: MODEL_URL
        value: https://drive.google.com/uc?export=download&id=11Yhi35TSYq1wZcYd2ReDcDB9BQL_9NN2
